# 仅用于本地开发，生产环境请使用 k8s 部署，并且不要使用任何弱密码

services:
  yapi-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      # 基础配置
      - YAPI_PORT=3000
      - YAPI_ADMIN_ACCOUNT=admin@admin.com
      - YAPI_TIMEOUT=120000
      
      # 数据库配置
      - YAPI_DB_SERVERNAME=mongodb
      - YAPI_DB_NAME=yapi
      - YAPI_DB_PORT=27017
      - YAPI_DB_USER=test1
      - YAPI_DB_PASS=test1
      - YAPI_DB_AUTH_SOURCE=admin

      - YAPI_CLOSE_REGISTER=true
      
      # 邮件配置 - 请根据需要自行配置
      - YAPI_MAIL_ENABLE=false
      # - YAPI_MAIL_HOST=smtp.163.com
      # - YAPI_MAIL_PORT=465
      # - YAPI_MAIL_FROM=your@email.com
      # - YAPI_MAIL_USER=your@email.com
      # - YAPI_MAIL_PASS=yourpassword

      # keycloak配置
      - YAPI_KEYCLOAK_ENABLE=true
      - YAPI_KEYCLOAK_REALM=master
      - YAPI_KEYCLOAK_CLIENT_ID=yapi
      - YAPI_KEYCLOAK_CLIENT_SECRET=2AVF4Q7PkSqRuT04NBRooMNkVWIksDaG
      - YAPI_KEYCLOAK_REDIRECT_URI=http://100.96.69.119:3000/api/user/oauth2/keycloak/callback
      - YAPI_KEYCLOAK_AUTH_SERVER_URL=https://keycloak.spacecycle.cn
      
      # 插件配置 - JSON格式的字符串
      - YAPI_PLUGINS=[{"name":"import-postman"},{"name":"import-har"},{"name":"advanced-mock"}]
      
    depends_on:
      - mongodb

  mongodb:
    image: mongo:8.0.9
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=test1
      - MONGO_INITDB_ROOT_PASSWORD=test1
      # 为 yapi 应用创建用户和数据库
      - MONGO_INITDB_DATABASE=yapi
    restart: unless-stopped

volumes:
  mongodb_data:
    driver: local